name: Auto Merge Pull Requests to Master

on:
  pull_request:
    types:
      - opened

jobs:
  merge:
    runs-on: ubuntu-latest
    
    steps:
      - name: Merge PR
        uses: pascalgn/automerge-action@v0.12.0
        with:
          github-token: ${{ secrets.CI_TOKEN }}
