name: Auto Merge Pull Requests to Master

on:
  pull_request:
    types:
      - opened

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Merge pull request
      run: |
        # Fetch the latest changes from the default remote repository
        git fetch origin
        # Merge the pull request branch
        git merge --no-ff ${{ github.event.pull_request.head.sha }}
        # Push the changes back to the remote repository
        git push origin master
      env:
        GITHUB_TOKEN: ${{ secrets.CI_TOKEN }}
