name: CI/CD

on:
  pull_request:
    branches:
      - master # Change 'main' to your default branch name (e.g., 'master')

jobs:

  merge:
    name: Merge on Success
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Merge Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.CI_MERGER_PAT }}
        run: |
          # Ensure the pull request is up to date with the base branch (master)
          git fetch origin master:master
          # Merge the pull request into master
          git checkout master
          git merge --no-ff ${{ github.event.pull_request.head.sha }}
          git push origin master
